modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/OreTweaker/issues"

[[mods]]
    modId="oretweaker"
    version="${file.jarVersion}"
    displayName="Ore Tweaker"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/Ore-Tweaker"
    credits=""
    authors="Ewy"
    description="Disable, tweak and add your own ore generation features for Minecraft Forge."

[[dependencies.oretweaker]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oretweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
